# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ffd-data:
    build:
      target: development
    image: ffc-ffd-data-development
    container_name: ffc-ffd-data-development
    ports:
      - "3004:3004"
      - "9004:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
