# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ffd-data:
    build:
      target: development
    image: ffc-ffd-data-development
    container_name: ffc-ffd-data-development
    ports:
      - "3004:3004"
      - "9004:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-ffd-data-redis:
    ports:
      - "6304:6379"
    volumes:
      - redis_data:/data
    command: redis-server --dir /data --save 5 1

volumes:
  redis_data:
