services:
  ffc-ffd-data:
    build:
      context: .
      target: production
    image: ffc-ffd-data
    container_name: ffc-ffd-data
    depends_on:
      - ffc-ffd-data-redis
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ffd-data-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      APIM_CLIENT_ID: ${APIM_CLIENT_ID}
      APIM_CLIENT_SECRET: ${APIM_CLIENT_SECRET}
      APIM_SCOPE: ${APIM_SCOPE}
      APIM_OCP_SUBSCRIPTION_KEY: ${APIM_OCP_SUBSCRIPTION_KEY}
      APIM_AUTHORIZATION_URL: ${APIM_AUTHORIZATION_URL}
      APIM_HOST: ${APIM_HOST}
      REDIS_HOST: ffc-ffd-data-redis

  ffc-ffd-data-redis:
    image: redis:6.2.7
