{{- include "ffc-helm-library.container-secret" (list . "ffc-ffd-data.container-secret") -}}
{{- define "ffc-ffd-data.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  APIM_CLIENT_SECRET: {{ quote .Values.apim.clientSecret }}
  REDIS_PASSWORD: {{ quote .Values.container.redisPassword }}
{{- end -}}
